### ISSUE TITLE
couldn't generate the demo

### ISSUE THREAD

**Issue by Falmi** [ZhengZerong/DeepHuman#2]
![image](https://user-images.githubusercontent.com/26068376/74274902-d899cc80-4d4d-11ea-8d40-ab33a89cde88.png)

What is my problem? I am expected to generate these missed files?

**Comment by vigorbird** [comment]
> ![image](https://user-images.githubusercontent.com/26068376/74274902-d899cc80-4d4d-11ea-8d40-ab33a89cde88.png)
> 
> What is my problem? I am expected to generate these missed files?

How do you solve this? I also meet this error

**Comment by vigorbird** [comment]
@Falmi How do you solve this problem?
